version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=cms_project
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony

  web:
    build: .
    ports:
      - 8080:80