<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWx5WQfI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWx5WQfI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWx5WQfI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWx5WQfI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWx5WQfI\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wx5WQfI',
    'container.build_id' => 'a9771bb3',
    'container.build_time' => 1618333918,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWx5WQfI');
