<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBVAAJdZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBVAAJdZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBVAAJdZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBVAAJdZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBVAAJdZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'BVAAJdZ',
    'container.build_id' => 'ac81fffe',
    'container.build_time' => 1618481369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBVAAJdZ');
