<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB4n4Ezk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB4n4Ezk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB4n4Ezk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB4n4Ezk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB4n4Ezk\App_KernelDevDebugContainer([
    'container.build_hash' => 'B4n4Ezk',
    'container.build_id' => '091d1b52',
    'container.build_time' => 1618425195,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB4n4Ezk');
